name: Lint

on:
  pull_request:
  push:


  jobs:
    lint:
      name: Lint
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v4

        - uses: action/setup-node@v3
          with:
            node-version: 20

        - run: npm install

        - run: npm run lint
